<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediaBrowser.Common" Version="4.10.0.24-beta2" />
        <PackageReference Include="MediaBrowser.Server.Core" Version="4.10.0.24-beta2" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="ThumbImage.jpg"/>
        <EmbeddedResource Include="ThumbImage.jpg"/>
        <EmbeddedResource Include="..\DefaultRegistry\plugins.json">
            <Link>DefaultRegistry\plugins.json</Link>
        </EmbeddedResource>
    </ItemGroup>
</Project>
